#openssl req -newkey rsa:2048 -sha256 -nodes -keyout TAB.key -x509 -days 365 -out YOURPUBLIC.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"
#openssl req -newkey rsa:2048 -sha256 -nodes -keyout YOURPRIVATE.key -x509 -days 365 -out YOURPUBLIC.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"
---
pid: /code/tab_autobot/tmp/pids/thin.pid
address: tab1004.ga
port: 443
timeout: 30
wait: 30
log: /code/tab_autobot/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
ssl: true
ssl-cert-file: /code/cert/TAB.crt
ssl-key-file: /code/cert/TAB.pem