1:
  field: 'buyer'
  question: 'Кто оплачивает?'
  answers:
    1: 'Я'
    2: 'Он'
    3: 'Пополам'
3:
  question: 'На сколько дней страхуется?'
  answers:
    1: '1 день'
    2: '1 неделя'
    3: '2 недели'
4:
  condition: '1/2'
  question: 'Введите описание товара'
5:
  condition: '1/2'
  question: 'Введите сумму сделки в долларах'
6:
  condition: '2/1'
  question: 'Введите WEX USD код на эту сумму'
7:
  condition: ''
  question: 'Проверьте информацию о сделке и нажмите старт'
  answers:
    1: 'Старт'
    2: 'Отмена'